### ISSUE TITLE
Some loops in 2ppc harris are not unrolled?

### ISSUE THREAD

**Issue by dillonhuff** [dillonhuff/clockwork#101]
@jeffsetter  some loops in `harris_sch6_2ppc` seem to be unrolled by two, but several others (for example `lgyy_s1_x`) are not unrolled by 2.

Is the intent for this application to have a mix of some inner loops unrolled by two and some not?

**Comment by jeffsetter** [comment]
This was not intended. It appears that I forgot to unroll the update loops. This is fixed in https://github.com/dillonhuff/clockwork/pull/102.
