### ISSUE TITLE
harris_sch3_1pp9c_compute.h uses 32 bit values for the kernel init functions

### ISSUE THREAD

**Issue by dillonhuff** [dillonhuff/clockwork#109]
@jeffsetter is this intended?

Example: https://github.com/dillonhuff/clockwork/blob/4672db925eb437ee84ce1aaa191cd4f673f0d2e6/harris_sch3_1pp9c_compute.h#L7

**Comment by jeffsetter** [comment]
It should work, but I'll change it to 16bits to be consistent.

**Comment by dillonhuff** [comment]
@jeffsetter thanks!

Actually the system will not work even if the width semantics are not a problem because the application-level regression tests also fail because the `buffer_port_widths` listed in the actual `prog` needs to be the same for the C++ compute units and the coreir compute units in order for both of them to compile.
