### ISSUE TITLE
Delete nn_apps

### ISSUE THREAD

**Issue by dillonhuff** [dillonhuff/clockwork#11]
@joyliu37 I just merged nn_apps and fixed the compute unit generation bugs. The application now runs and generates code to the file `cnn_conv_layer.cpp`

Please delete the nn_apps branch and check out a new branch off of master.

**Comment by joyliu37** [comment]
Thanks! I found in the `cnn_conv_layer.cpp`, the sector has unsupported offset. Is that means the address pattern is not supported by current codegen ?

**Comment by joyliu37** [comment]
Oops my bad. I did not turn on the line wrap. there are some complex logic before that assertion.

**Comment by dillonhuff** [comment]
@joyliu37 glad its working. LMK what your next step in getting app compiled to the CGRA will be.
