### ISSUE TITLE
harris_sch4_1pp3c_compute.h uses 32 bit values for the kernel init functions

### ISSUE THREAD

**Issue by dillonhuff** [dillonhuff/clockwork#110]
@jeffsetter I assume this is related to #109 

Looks like the same issue: https://github.com/dillonhuff/clockwork/blob/4672db925eb437ee84ce1aaa191cd4f673f0d2e6/harris_sch4_1pp3c_compute.h#L7

**Comment by jeffsetter** [comment]
It should work, but I'll change it to 16bits to be consistent.
