### ISSUE TITLE
Garnet CGRA Mapping was Accidentally Commented out

### ISSUE THREAD

**Issue by joyliu37** [dillonhuff/clockwork#115]
It won't map to CGRA if you disable the cgramapper pass. Shall we uncomment it? 
https://github.com/dillonhuff/clockwork/blob/7862786af09848e1bc304838a30a0f644b12f28c/coreir_backend.cpp#L2260

**Comment by dillonhuff** [comment]
@joyliu37 uncommenting it breaks my resnet test. LMK if you see the same thing on your end.
