### ISSUE TITLE
Bug in binary search for minimum operation delay

### ISSUE THREAD

**Issue by joyliu37** [dillonhuff/clockwork#139]
https://github.com/dillonhuff/clockwork/blob/bfc8323c0b8d25948461e1e50cf0cc60d4efbf57/prog.cpp#L7602

Should this be (left + right)/2 instead of (left-right)/2 in binary search?

**Comment by dillonhuff** [comment]
@joyliu37 that code produces the results I expect for all the examples in cgra-flow, so I would just leave it unless it is producing a bad schedule for another app.

**Comment by joyliu37** [comment]
It produce an infinite loop for Resnet scheduling in the lake-tests.

**Comment by dillonhuff** [comment]
Does the change you suggested fix it? If so just make the change and merge to master.

**Comment by joyliu37** [comment]
Yeah. 
Are dhuff-test and cgra-flow the regression tests a PR must pass?

**Comment by dillonhuff** [comment]
Yes
