### ISSUE TITLE
Issue with modulus

### ISSUE THREAD

**Issue by jeffsetter** [dillonhuff/clockwork#151]
I have an issue using a modulus operator in this upsample example. Is there an issue with the way it's written?

[mod_example_memory.txt](https://github.com/dillonhuff/clockwork/files/6027179/mod_example_memory.txt)
[mod_example_compute.txt](https://github.com/dillonhuff/clockwork/files/6027180/mod_example_compute.txt)

**Comment by dillonhuff** [comment]
@jeffsetter since you did not say what the issue was I don't actually know if I fixed the problem. But I fixed the only problem that I ran into with running the unoptimized version of that app. Please file another issue if there is something else.
