### ISSUE TITLE
Bank selection logic generation fails

### ISSUE THREAD

**Issue by jeffsetter** [dillonhuff/clockwork#156]
I'm having trouble generating the unoptimized code for lucas_kanade. I encounter this error:
```
cd ./bin && LD_LIBRARY_PATH=/nobackup/setter/h2h/hwbuffer/polyir/../clockwork/lib:/nobackup/setter/h2h/hwbuffer/polyir/../coreir/lib ./clockwork_codegen unopt >/dev/null; cd ..
clockwork_codegen: ubuffer.cpp:4159: void generate_select(CodegenOptions&, std::ostream&, const string&, UBuffer&): Assertion `buf.bank_list.size() == 1' failed.
bash: line 1: 15212 Aborted                 (core dumped) LD_LIBRARY_PATH=/nobackup/setter/h2h/hwbuffer/polyir/../clockwork/lib:/nobackup/setter/h2h/hwbuffer/polyir/../coreir/lib ./clockwork_codegen unop$
```
Do you know what the issue is?

The files for lucas_kanade are here:
[lucas_kanade_compute.txt](https://github.com/dillonhuff/clockwork/files/6158372/lucas_kanade_compute.txt)
[lucas_kanade_memory.txt](https://github.com/dillonhuff/clockwork/files/6158373/lucas_kanade_memory.txt)

**Comment by dillonhuff** [comment]
The program contains a buffer that is read but never written apparently:

```
Error: fx_stencil has 9 readers, but it is never written.
Assertion failed: (false), function sanity_check, file prog.cpp, line 3560.
```

You can reproduce this check like so: https://github.com/dillonhuff/clockwork/blob/703a27634eb2d58350c5c1a24c7b64779d8587e9/build_set_test.cpp#L25235-L25237

**Comment by jeffsetter** [comment]
Thanks, that resolved this part of the problem. There is a subsequent problem with $floor and $rtoi, but I'll create another issue.
