### ISSUE TITLE
multilinear_address code generation uses stack memory, lead to segfault when generating large memory

### ISSUE THREAD

**Issue by joyliu37** [dillonhuff/clockwork#167]
When Jeff and me test a large application with global buffer, we notice that the unoptimized regression test will give us seg fault. 
After a quick debugging, I found the `multi linear address` codegen option will generate cache in stack memory(static array). 
I also find there is a `linear_address` codegen options that we could use and it assign heap array. 
https://github.com/dillonhuff/clockwork/blob/f956c197d2513be98a72d2d64d27a5cf0035c110/ubuffer.cpp#L372-L500

I am planning to use `linear_addr` for all the default c++ codegen. I do not know if there is any problem if we make that changes. 
https://github.com/dillonhuff/clockwork/blob/f956c197d2513be98a72d2d64d27a5cf0035c110/prog.cpp#L2678-L2689

**Comment by dillonhuff** [comment]
That should be fine. LMK if something else breaks because of it.
