### ISSUE TITLE
Question about Get_lexmax_event function

### ISSUE THREAD

**Issue by joyliu37** [dillonhuff/clockwork#24]
I found I accidentally use the `get_lexmax_event` function in the bankmerge test. I do not know if these broken some test.  https://github.com/dillonhuff/clockwork/blob/4388460404955112ee95d11a7de9b2ccb622cb7c/ubuffer.cpp#L1040 

I think this function is just figure out the write statement that the read statement depend on. I do not know what the following code's purpose.https://github.com/dillonhuff/clockwork/blob/4388460404955112ee95d11a7de9b2ccb622cb7c/ubuffer.cpp#L980-L989. It's like filtering out some redundant dependency, but I am not sure what is eliminated. Could you help me to understand this.

**Comment by dillonhuff** [comment]
@joyliu37 I'm not sure what you mean. Is it a problem that you use `get_lexmax_events`?
