### ISSUE TITLE
Halide Generate Address Dimension Sequence

### ISSUE THREAD

**Issue by joyliu37** [dillonhuff/clockwork#44]
I want to double check the halide generated clockwork dimension sequence. 
For instance
 `  hcompute_conv_stencil_7->add_load("hw_input_stencil", "7", "(conv_s1_r_x + conv_s1_x)", "(conv_s1_r_y + conv_s1_y)");`
Does this mean `add_load(buf_name, inner_most<-, ->outer most)` 
Or `add_load(buf_name, outer_most<-, ->inner most)` 
I think clockwork follow the C++ array dimension sequence.

**Comment by jeffsetter** [comment]
I'm intending that these memory operations have indices from inner-most to outer-most. 
```
add_load(buf_name, inner_most<-, ->outer most)

**Comment by joyliu37** [comment]
Could you flip the dimension from outer most to inner most?

**Comment by jeffsetter** [comment]
What are you asking? Do you want it to be 
```add_load(buf_name, inner_most<-, ->outer most)```

Or are you asking if you're able to switch the order in Halide?

**Comment by joyliu37** [comment]
I want it to be 
`add_load(buf_name, outer_most<-, ->inner most)`

**Comment by jeffsetter** [comment]
Changed Halide to generate it in that order.
