### ISSUE TITLE
Question about hardware schedule variable ddiff

### ISSUE THREAD

**Issue by joyliu37** [dillonhuff/clockwork#63]
I was revisiting the hardware_schedule method in https://github.com/dillonhuff/clockwork/blob/a6a7e2c7bc0d15c3559e8b7388faf4a3507b95bf/app.cpp#L1353
And I found there is a modulo schedule variable you solved in the end has the suffix `_ddiff`. I am wondering what does this variable stand for. Is that related to the dependency distance between two statement?

**Comment by dillonhuff** [comment]
@joyliu37 the `_ddiff` suffix is not related to dependence distance. Its hard to explain in text.
